groups/urls.py
from django.conf.urls import patterns, url

from .views import (
    GroupListView, GroupStudentsListView, GroupCreateView, GroupEditView,
    GroupDeleteView
)


urlpatterns = patterns(
    '',
    url(r'^$', GroupListView.as_view(), name='groups_list'),
    url(r'^create/$', GroupCreateView.as_view(), name='group_create'),
    url(r'^(?P<group_id>\d+)/students/$', GroupStudentsListView.as_view(),
        name='group_students'),
    url(r'^(?P<group_id>\d+)/edit/$', GroupEditView.as_view(),
        name='group_edit'),
    url(r'^(?P<group_id>\d+)/delete/$', GroupDeleteView.as_view(),
        name='group_delete'),
)

students/urls.py
from django.conf.urls import patterns, url

from .views import (
    StudentListView, StudentCreateView, StudentEditView, StudentDeleteView
)


urlpatterns = patterns(
    '',
    url(r'^$', StudentListView.as_view(), name='students_list'),
    url(r'^create/$', StudentCreateView.as_view(), name='student_create'),
    url(r'^(?P<student_id>\d+)/edit/$', StudentEditView.as_view(),
        name='student_edit'),
    url(r'^(?P<student_id>\d+)/delete/$', StudentDeleteView.as_view(),
        name='student_delete'),
)

urls.py
from django.conf import settings
from django.conf.urls import patterns, include, url
from django.contrib.auth import views as auth_views
from django.contrib import admin
from django.core.urlresolvers import reverse_lazy
from yawdadmin import admin_site

from core.views import UserAuthenticationView, IndexView


admin.autodiscover()
admin_site._registry.update(admin.site._registry)


urlpatterns = patterns('',
    url(r'^login/$', UserAuthenticationView.as_view(), name='auth_login'),
    url(r'^logout/$', auth_views.logout,
        {'next_page': reverse_lazy(settings.LOGOUT_REDIRECT_URL)},
        name='auth_logout'),

    url(r'^$', IndexView.as_view(), name='index'),
    url(r'^students/', include('students.urls', namespace='students')),
    url(r'^groups/', include('groups.urls', namespace='groups')),
    url(r'^admin/', include(admin_site.urls)),
)

groups/forms.py
from django import forms

from core.models import Group
from core.forms_mixin import BootstrapForm


class GroupForm(BootstrapForm, forms.ModelForm):
    class Meta:
        model = Group

groups/views.py
from braces.views import LoginRequiredMixin
from django.core.urlresolvers import reverse_lazy
from django.views.generic import ListView, CreateView, UpdateView, DeleteView

from core.models import Group, Student
from .forms import GroupForm


class GroupListView(LoginRequiredMixin, ListView):
    template_name = 'groups_list.html'
    paginate_by = 20
    context_object_name = 'groups'
    model = Group


class GroupStudentsListView(LoginRequiredMixin, ListView):
    template_name = 'group_students_list.html'
    paginate_by = 20
    context_object_name = 'students'
    pk_url_kwarg = 'group_id'
    model = Student

    def get_context_data(self, **kwargs):
        context = super(GroupStudentsListView, self).get_context_data(**kwargs)
        context['group_name'] = self.get_group()
        return context

    def get_queryset(self):
        return Student.objects.filter(group=self.get_group())

    def get_group(self):
        return Group.objects.filter(
            pk=self.kwargs.get(self.pk_url_kwarg)
        ).first()


class GroupCreateView(LoginRequiredMixin, CreateView):
    template_name = 'group_create.html'
    success_url = reverse_lazy('groups:groups_list')
    form_class = GroupForm
    model = Group

    def form_valid(self, form):
        self.object = form.save()
        self.object.warden.group = self.object
        self.object.warden.save()
        return super(GroupCreateView, self).form_valid(form)


class GroupEditView(LoginRequiredMixin, UpdateView):
    template_name = 'group_edit.html'
    success_url = reverse_lazy('groups:groups_list')
    pk_url_kwarg = 'group_id'
    form_class = GroupForm
    model = Group


class GroupDeleteView(LoginRequiredMixin, DeleteView):
    success_url = reverse_lazy('groups:groups_list')
    pk_url_kwarg = 'group_id'
    model = Group

groups/templates/group_create.html
{% extends 'base.html' %}

{% block title %}Create new group{% endblock %}

{% block content %}
<div class="row">
  <div class="col-md-3 col-xs-offset-4">
    <form action="" method="post">
      {% csrf_token %}
      {% for field in form %}
        <div class="form-group{% if field.errors %} has-error{% endif %}">
          <label for="{{ field.id_for_label }}">{{ field.label }}:</label>
          {{ field }}
          {% if field.errors %}
            <span class="text-danger">{{ field.errors.0 }}</span>
          {% endif %}
        </div>
      {% endfor %}
      <button type="submit" class="btn btn-info">Create</button>
    </form>
  </div>
</div>
{% endblock %}

groups/templates/group_edit.html
{% extends 'base.html' %}

{% block title %}Edit {{ form.name.value }} group{% endblock %}

{% block content %}
<div class="row">
  <div class="col-md-3 col-xs-offset-4">
    <form action="" method="post">
      {% csrf_token %}
      {% for field in form %}
        <div class="form-group{% if field.errors %} has-error{% endif %}">
          <label for="{{ field.id_for_label }}">{{ field.label }}:</label>
          {{ field }}
          {% if field.errors %}
            <span class="text-danger">{{ field.errors.0 }}</span>
          {% endif %}
        </div>
      {% endfor %}
      <button type="submit" class="btn btn-info">Edit</button>
    </form>
  </div>
</div>
{% endblock %}

groups/templates/group_students_list.html
{% extends 'base.html' %}

{% block title %}{{ group_name }} Students list{% endblock %}

{% block content %}

<p><a href="{% url 'students:student_create' %}">Create new student</a></p>

<table class="table table-striped">
  <tr>
    <th>Student name</th>
    <th>Group</th>
    <th>Birth date</th>
    <th>Ticket number</th>
    <th>Action</th>
  </tr>
  {% for student in students %}
  <tr>
    <td>{{ student.name }}</td>
    <td>{{ student.group }}</td>
    <td>{{ student.birth_date }}</td>
    <td>{{ student.ticket_number }}</td>
    <td>
      <a href="{% url 'students:student_edit' student.id %}">Edit</a>
      /
      <a href="{% url 'students:student_delete' student.id %}" onclick="document.getElementById({{ student.id }}).submit(); return false;">Delete</a>
      <form id="{{ student.id }}" action="{% url 'students:student_delete' student.id %}" method="post">{% csrf_token %}</form>
    </td>
  </tr>
  {% endfor %}
</table>

{% endblock %}

groups/templates/groups_list.html
{% extends 'base.html' %}

{% block title %}Groups list{% endblock %}

{% block content %}

<p><a href="{% url 'groups:group_create' %}">Create new group</a></p>

<table class="table table-striped">
  <tr>
    <th>Group name</th>
    <th>Warden</th>
    <th>Students count</th>
    <th>Action</th>
  </tr>
  {% for group in groups %}
  <tr>
    <td><a href="{% url 'groups:group_students' group.id %}">{{ group.name }}</a></td>
    <td>{{ group.warden.name }}</td>
    <td>{{ group.students_count }}</td>
    <td>
      <a href="{% url 'groups:group_edit' group.id %}">Edit</a>
      /
      <a href="{% url 'groups:group_delete' group.id %}" onclick="document.getElementById({{ group.id }}).submit(); return false;">Delete</a>
      <form id="{{ group.id }}" action="{% url 'groups:group_delete' group.id %}" method="post">{% csrf_token %}</form>
    </td>
  </tr>
  {% endfor %}
</table>

{% endblock %}