groups/urls.py
from django.conf.urls import patterns, url

from .views import (
    GroupListView, GroupStudentsListView, GroupCreateView, GroupEditView,
    GroupDeleteView
)


urlpatterns = patterns(
    '',
    url(r'^$', GroupListView.as_view(), name='groups_list'),
    url(r'^create/$', GroupCreateView.as_view(), name='group_create'),
    url(r'^(?P<group_id>\d+)/students/$', GroupStudentsListView.as_view(),
        name='group_students'),
    url(r'^(?P<group_id>\d+)/edit/$', GroupEditView.as_view(),
        name='group_edit'),
    url(r'^(?P<group_id>\d+)/delete/$', GroupDeleteView.as_view(),
        name='group_delete'),
)

students/urls.py
from django.conf.urls import patterns, url

from .views import (
    StudentListView, StudentCreateView, StudentEditView, StudentDeleteView
)


urlpatterns = patterns(
    '',
    url(r'^$', StudentListView.as_view(), name='students_list'),
    url(r'^create/$', StudentCreateView.as_view(), name='student_create'),
    url(r'^(?P<student_id>\d+)/edit/$', StudentEditView.as_view(),
        name='student_edit'),
    url(r'^(?P<student_id>\d+)/delete/$', StudentDeleteView.as_view(),
        name='student_delete'),
)

urls.py
from django.conf import settings
from django.conf.urls import patterns, include, url
from django.contrib.auth import views as auth_views
from django.contrib import admin
from django.core.urlresolvers import reverse_lazy
from yawdadmin import admin_site

from core.views import UserAuthenticationView, IndexView


admin.autodiscover()
admin_site._registry.update(admin.site._registry)


urlpatterns = patterns('',
    url(r'^login/$', UserAuthenticationView.as_view(), name='auth_login'),
    url(r'^logout/$', auth_views.logout,
        {'next_page': reverse_lazy(settings.LOGOUT_REDIRECT_URL)},
        name='auth_logout'),

    url(r'^$', IndexView.as_view(), name='index'),
    url(r'^students/', include('students.urls', namespace='students')),
    url(r'^groups/', include('groups.urls', namespace='groups')),
    url(r'^admin/', include(admin_site.urls)),
)

templates/base.html
{% load tags static %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=970">
    <meta name="description" content="">
    <meta name="author" content="Bliznuk Philipp">
    <title>Students | {% block title %}{% endblock title %}</title>
    <link href='{% static 'css/bootstrap.css' %}' rel='stylesheet' type='text/css'>

    {% block extrahead %}{% endblock extrahead %}
  </head>
  <body>

  <div class="container-fluid">
    <div class="row">
      <div class="panel panel-default">
        <div class="panel-body bg-info">
          <p class="col-md-12 text-right">
            {% if request.user.is_authenticated %}
              Hello {% edit_list request.user %}, <a href="{% url 'auth_logout' %}">Logout</a>
            {% else %}
              <a href="{% url 'auth_login' %}">Login</a>
            {% endif %}
          </p>
        </div>
      </div>
    </div>

    <div class="row">
      <p class="col-md-12 text-center">
        <a href="{% url 'students:students_list' %}">Students</a> |
        <a href="{% url 'groups:groups_list' %}">Groups</a>
      </p>
    </div>

    {% block content %}{% endblock content %}
    {% block extra_html %}{% endblock %}

    <script src="//ajax.googleapis.com/ajax/libs/jquery/2.1.4/jquery.min.js"></script>
    <script type="text/javascript" src="{% static 'js/bootstrap.min.js' %}"></script>
    {% block extra_js %}{% endblock %}
  </div>
  </body>
</html>

templates/login.html
{% extends "base.html" %}

{% block title %}Login{% endblock %}

{% block content %}
<div class="row">
  <div class="col-md-2 col-md-offset-5">
    {% if form.errors %}
      <p class="text-danger">
        {% for key, error in form.errors.iteritems %}
          {{ error }}<br />
        {% endfor %}
      </p>
    {% endif %}
    <form action="" method="post" class="form-horizontal">
    {% csrf_token %}
      <input type="hidden" name="next" value="{{ request.GET.next }}">
      {% for field in form %}
        <div class="form-group{% if field.errors %} has-error{% endif %}">
          <label for="{{ field.id_for_label }}">{{ field.label }}:</label>
          {{ field }}
          {% if field.errors %}
            <span class="text-danger">{{ field.errors.0 }}</span>
          {% endif %}
        </div>
      {% endfor %}

      <div class="form-group">
        <button type="submit" class="btn btn-info">Sign in</button>
      </div>
    </form>
  </div>
</div>
{% endblock %}